/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as IndexRouteImport } from './routes/index';
import { Route as BoardsIndexRouteImport } from './routes/boards/index';
import { Route as BoardsBoardIdRouteImport } from './routes/boards/$boardId';
import { Route as SigninIndexRouteImport } from './routes/signin/index';
import { Route as SignupIndexRouteImport } from './routes/signup/index';
import { Route as BoardsBoardIdSettingsRouteImport } from './routes/boards/$boardId_.settings';
import { Route as BoardsBoardIdIssuesIndexRouteImport } from './routes/boards/$boardId_.issues.index';
import { Route as BoardsBoardIdIssuesIssueIdRouteImport } from './routes/boards/$boardId_.issues.$issueId';

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const BoardsIndexRoute = BoardsIndexRouteImport.update({
  id: '/boards/',
  path: '/boards/',
  getParentRoute: () => rootRouteImport,
} as any);
const BoardsBoardIdRoute = BoardsBoardIdRouteImport.update({
  id: '/boards/$boardId',
  path: '/boards/$boardId',
  getParentRoute: () => rootRouteImport,
} as any);
const SigninIndexRoute = SigninIndexRouteImport.update({
  id: '/signin/',
  path: '/signin/',
  getParentRoute: () => rootRouteImport,
} as any);
const SignupIndexRoute = SignupIndexRouteImport.update({
  id: '/signup/',
  path: '/signup/',
  getParentRoute: () => rootRouteImport,
} as any);
const BoardsBoardIdSettingsRoute = BoardsBoardIdSettingsRouteImport.update({
  id: '/boards/$boardId_/settings',
  path: '/boards/$boardId/settings',
  getParentRoute: () => rootRouteImport,
} as any);
const BoardsBoardIdIssuesIndexRoute =
  BoardsBoardIdIssuesIndexRouteImport.update({
    id: '/boards/$boardId_/issues/',
    path: '/boards/$boardId/issues/',
    getParentRoute: () => rootRouteImport,
  } as any);
const BoardsBoardIdIssuesIssueIdRoute =
  BoardsBoardIdIssuesIssueIdRouteImport.update({
    id: '/boards/$boardId_/issues/$issueId',
    path: '/boards/$boardId/issues/$issueId',
    getParentRoute: () => rootRouteImport,
  } as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/boards/$boardId': typeof BoardsBoardIdRoute;
  '/boards/': typeof BoardsIndexRoute;
  '/signin/': typeof SigninIndexRoute;
  '/signup/': typeof SignupIndexRoute;
  '/boards/$boardId/settings': typeof BoardsBoardIdSettingsRoute;
  '/boards/$boardId/issues/$issueId': typeof BoardsBoardIdIssuesIssueIdRoute;
  '/boards/$boardId/issues/': typeof BoardsBoardIdIssuesIndexRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/boards/$boardId': typeof BoardsBoardIdRoute;
  '/boards': typeof BoardsIndexRoute;
  '/signin': typeof SigninIndexRoute;
  '/signup': typeof SignupIndexRoute;
  '/boards/$boardId/settings': typeof BoardsBoardIdSettingsRoute;
  '/boards/$boardId/issues/$issueId': typeof BoardsBoardIdIssuesIssueIdRoute;
  '/boards/$boardId/issues': typeof BoardsBoardIdIssuesIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/boards/$boardId': typeof BoardsBoardIdRoute;
  '/boards/': typeof BoardsIndexRoute;
  '/signin/': typeof SigninIndexRoute;
  '/signup/': typeof SignupIndexRoute;
  '/boards/$boardId_/settings': typeof BoardsBoardIdSettingsRoute;
  '/boards/$boardId_/issues/$issueId': typeof BoardsBoardIdIssuesIssueIdRoute;
  '/boards/$boardId_/issues/': typeof BoardsBoardIdIssuesIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/boards/$boardId'
    | '/boards/'
    | '/signin/'
    | '/signup/'
    | '/boards/$boardId/settings'
    | '/boards/$boardId/issues/$issueId'
    | '/boards/$boardId/issues/';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/boards/$boardId'
    | '/boards'
    | '/signin'
    | '/signup'
    | '/boards/$boardId/settings'
    | '/boards/$boardId/issues/$issueId'
    | '/boards/$boardId/issues';
  id:
    | '__root__'
    | '/'
    | '/boards/$boardId'
    | '/boards/'
    | '/signin/'
    | '/signup/'
    | '/boards/$boardId_/settings'
    | '/boards/$boardId_/issues/$issueId'
    | '/boards/$boardId_/issues/';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  BoardsBoardIdRoute: typeof BoardsBoardIdRoute;
  BoardsIndexRoute: typeof BoardsIndexRoute;
  SigninIndexRoute: typeof SigninIndexRoute;
  SignupIndexRoute: typeof SignupIndexRoute;
  BoardsBoardIdSettingsRoute: typeof BoardsBoardIdSettingsRoute;
  BoardsBoardIdIssuesIssueIdRoute: typeof BoardsBoardIdIssuesIssueIdRoute;
  BoardsBoardIdIssuesIndexRoute: typeof BoardsBoardIdIssuesIndexRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/boards/': {
      id: '/boards/';
      path: '/boards';
      fullPath: '/boards/';
      preLoaderRoute: typeof BoardsIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/boards/$boardId': {
      id: '/boards/$boardId';
      path: '/boards/$boardId';
      fullPath: '/boards/$boardId';
      preLoaderRoute: typeof BoardsBoardIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/signin/': {
      id: '/signin/';
      path: '/signin';
      fullPath: '/signin/';
      preLoaderRoute: typeof SigninIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/signup/': {
      id: '/signup/';
      path: '/signup';
      fullPath: '/signup/';
      preLoaderRoute: typeof SignupIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/boards/$boardId_/settings': {
      id: '/boards/$boardId_/settings';
      path: '/boards/$boardId/settings';
      fullPath: '/boards/$boardId/settings';
      preLoaderRoute: typeof BoardsBoardIdSettingsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/boards/$boardId_/issues/': {
      id: '/boards/$boardId_/issues/';
      path: '/boards/$boardId/issues';
      fullPath: '/boards/$boardId/issues/';
      preLoaderRoute: typeof BoardsBoardIdIssuesIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/boards/$boardId_/issues/$issueId': {
      id: '/boards/$boardId_/issues/$issueId';
      path: '/boards/$boardId/issues/$issueId';
      fullPath: '/boards/$boardId/issues/$issueId';
      preLoaderRoute: typeof BoardsBoardIdIssuesIssueIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoardsBoardIdRoute: BoardsBoardIdRoute,
  BoardsIndexRoute: BoardsIndexRoute,
  SigninIndexRoute: SigninIndexRoute,
  SignupIndexRoute: SignupIndexRoute,
  BoardsBoardIdSettingsRoute: BoardsBoardIdSettingsRoute,
  BoardsBoardIdIssuesIssueIdRoute: BoardsBoardIdIssuesIssueIdRoute,
  BoardsBoardIdIssuesIndexRoute: BoardsBoardIdIssuesIndexRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
